### ISSUE TITLE
Deployment clarification

### ISSUE THREAD

**Issue by chandrikashivanna** [dereklegenzoff/azure-search-react-template#25]
How this application can be deployed in App Service Web App (not as Static web app, Static web app is still preview so it cant be used in production) ?

**Comment by dereklegenzoff** [comment]
To publish this as a standard App Service Web App, the main things you'll need to do are:
1. Deploy the Azure functions. You can [publish the functions from within VS Code](https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs-code?tabs=nodejs).
2. Update the routes for the various API calls, such as in `Search.js` and `Details.js`, to point to the Azure Function URLs
3. Deploy the react app to app service. This [video](https://azure.microsoft.com/en-us/resources/videos/build-and-deply-nodejs-and-react-apps-with-vscode-appservice-and-cosmosdb/) shows how this can be done from within VS Code

**Comment by dereklegenzoff** [comment]
Hi @chandrikashivanna - there hasn't been any activity on this thread so I'm going to go ahead and close this issue. Feel free to reopen it if you have any additional questions.
