### ISSUE TITLE
Duplicate Search Api Calls

### ISSUE THREAD

**Issue by scott-alvis** [dereklegenzoff/azure-search-react-template#31]
Thank you for this great template.

It appears the each request to search api is happening twice when searching or paging. Is this intentional or a possible bug?

The screen shots below are for a single request.

<img width="740" alt="Screen Shot 2021-05-26 at 5 02 31 PM" src="https://user-images.githubusercontent.com/11140583/119746025-4df6b700-be44-11eb-8e54-44f72b66e2aa.png">

<img width="910" alt="Screen Shot 2021-05-26 at 5 04 54 PM" src="https://user-images.githubusercontent.com/11140583/119746113-88f8ea80-be44-11eb-9f1f-3be6bce1f594.png">

**Comment by dereklegenzoff** [comment]
Thanks for flagging this! This does appear to be a bug. Let me investigate and see if I can find a fix.

**Comment by scott-alvis** [comment]
Thank you for looking into the issue. I was trying to debug but for some reason I keep getting unbounded break points, still a little new to debugging react/node apps.

**Comment by scott-alvis** [comment]
> Thanks for flagging this! This does appear to be a bug. Let me investigate and see if I can find a fix.

Thank you for looking into the issue. 
I was trying to debug but for some reason I keep getting unbounded break points, still a little new to debugging react/node apps.

**Comment by dereklegenzoff** [comment]
No problem! It's a bit tricky to debug because `useEffect` causes the page to re-render. In this case it appears there were two issues:
1. I was updating the value of `skip` in the first `useEffect`. That was causing the function to be called twice when paging.
2. Whenever the search term was updated, the filters were being reset in the second `useEffect` causing the Search API call to send twice

I also realized the suggestion API was getting called more frequently than desired. I'll have a PR in shortly that I think fixes the issue.

**Comment by dereklegenzoff** [comment]
Just merged the PR as everything worked well on the test site. Let me know if you still have the issue or run into anything else.

**Comment by scott-alvis** [comment]
> Just merged the PR as everything worked well on the test site. Let me know if you still have the issue or run into anything else.

Thanks so much for the quick turn around. I will take a look at the changes and report back if I find any issues.

I do have one feature request, support for facets of type Collection(Edm.ComplexType). For example the Rooms field in the hotel sample data. I looked at the https://github.com/Azure-Samples/AzSearch.js and https://github.com/Azure-Samples/AzSearchStore projects but they don't support faceting on Collection(Edm.ComplexType).

Thanks again for all your help!

**Comment by dereklegenzoff** [comment]
Thanks! I'll take a look at that to see if I'm able to add that if it doesn't work already. I probably won't have quite as fast of a turnaround though. 

By the way, working on a separate project today, I discovered I was sometimes hitting multiple queries on pagination again so the issue might apply to this repo too. If you run into this you may need to update this [line](https://github.com/dereklegenzoff/azure-search-react-template/blob/master/src/components/Pager/Pager.js#L49) to include `parseInt` as such (the variable was sometimes switching back and forth between int and string causing multiple renders):

```javascript
<button className="page-link" id={i} onClick={(e) => setSelectedPage(parseInt(e.currentTarget.id))}>{i}</button>
```

**Comment by scott-alvis** [comment]
Thanks, I'll add that to my version.

I did notice the issue with pagination sometimes showing the wrong results set but assumed it was because of the double search calls.

**Comment by scott-alvis** [comment]
One other thing I just found. When on the search page when using the search box (either the enter key or clicking the button) does not update the query string. It takes two submits for the query string to get updated. I can open another issue if you like.

Thanks!!!

**Comment by dereklegenzoff** [comment]
Good catch. Looks like I introduced that bug in my PR yesterday (was just passing a stale variable to the URL). I fixed it and the item mentioned above in this PR: [https://github.com/dereklegenzoff/azure-search-react-template/pull/33/files](https://github.com/dereklegenzoff/azure-search-react-template/pull/33/files)

**Comment by scott-alvis** [comment]
Thanks again for the quick turnaround.
