### ISSUE TITLE
Missing Backend / Proxy Config? Proxy error: Could not proxy request /.auth/me from localhost:3000 to http://localhost:7071/.

### ISSUE THREAD

**Issue by jarfer** [dereklegenzoff/azure-search-react-template#37]
Hi,

Following the steps as documented here builds and runs the site, but the search does not appear to be functional, it gives:

Proxy error: Could not proxy request /.auth/me from localhost:3000 to http://localhost:7071/.

I'm not sure if there's some configuration not documented here which I need to do: but what puzzles me is why are you defining a proxy for port 7071 without anything to connect to?  

Sorry if I've misunderstood - and if this is a separate project we are supposed to setup not outlined here

Kind regards,

Roger Davies

**Comment by dereklegenzoff** [comment]
Hi @jarfer - you need to make sure you run both the react front-end as well as the azure function project. You should run `npm install` and `npm start` from both the main folder and the api folder. That error message looks like the azure functions aren't up and running.
