### ISSUE TITLE
Proxy Error

### ISSUE THREAD

**Issue by nickhalmagyi** [dereklegenzoff/azure-search-react-template#46]
I have successfully deployed this repo on azure, modifying it to consume my custom index.

But when trying to deploy locally, I get the error in the VS-code terminal

Proxy error: Could not proxy request /.auth/me from localhost:3000 to http://127.0.0.1:7071.

The "Sign In" button on the top-right of the screen is absent and the search does not find any items.

**Comment by dereklegenzoff** [comment]
That first part is expected - the auth endpoint only works when the application is deployed because it's not available locally. If you deploy the app, the sign in functionality should work.

You should be seeing search results though. Could you share some more details on what's happening there? Do you see any errors if you right click on the web page -> hit inspect -> and then look at the console?

**Comment by nickhalmagyi** [comment]
Hi, thanks for your reply.

<img width="557" alt="Screen Shot 2022-10-13 at 9 42 49 am" src="https://user-images.githubusercontent.com/22376971/195461346-de36a1e8-1181-46fe-8c33-7f08e438ce9b.png">

that's a screenshot of the console

**Comment by dereklegenzoff** [comment]
Thanks! One more request - could you share the error output from the command line where you're running the Azure Function. There should be some errors related to that API call that will help us understand why the Search API is returning a 500.

**Comment by nickhalmagyi** [comment]
does this help?

![Screen Shot 2022-10-14 at 10 55 16 am](https://user-images.githubusercontent.com/22376971/195732670-82581597-7f4c-4bb9-b254-0ff40904e2ac.png)

![Screen Shot 2022-10-14 at 10 54 06 am](https://user-images.githubusercontent.com/22376971/195732312-7c94fea9-9967-49b7-abef-b15bb762681e.png)

![Screen Shot 2022-10-14 at 10 56 07 am](https://user-images.githubusercontent.com/22376971/195732748-d29a068c-5d0b-4069-baa9-f62a2cabae4c.png)

**Comment by dereklegenzoff** [comment]
Do you have the API project running anywhere? Normally that will be running in a separate terminal and that's the project that will have the errors we're looking for. If it's not running, you can create a second terminal and run:
1. `cd api` to navigate into the api folder
2. `func start` or `npm start` (i forget which off the top of my head) to run the azure function project.

**Comment by nickhalmagyi** [comment]
ah right, I didn't see that in the README but I have now got it to work.

I did however need to use this
https://github.com/Azure/Azure-Functions/issues/1987#issuecomment-952420935
since I was getting an error from Azure Functions extension.

thanks for your help

**Comment by dereklegenzoff** [comment]
Great! Glad you got it figured out. And thanks for calling out the error you ran into with the Azure Functions; that's probably a good thing for me to update now that this repo is a bit older.

I'm going to close this issue for now. Feel free to re-open it if you run into any issues in the future.

**Comment by isspid** [comment]
@nickhalmagyi Hey, how are you? I am having the same problem as you. 
![image](https://user-images.githubusercontent.com/91065022/219003506-28044567-8a33-41e8-8771-cfbf2a2724ad.png)
![image](https://user-images.githubusercontent.com/91065022/219003614-88dee96b-237d-4197-a785-ce8a1b1e37dd.png)
Could you please help me finding a solution, I am feeling a little bit lost.
